### ISSUE TITLE
Publish之后的软件在GlowWindow由最大化切换到最小化时抛出异常：内存位置访问无效。

### ISSUE THREAD

**Issue by Anestis271** [NaBian/HandyControl#1465]
### Describe the bug

我的主程序窗口为GlowWindow，在publish之前，无论是Debug还是Release都没有任何问题，但publish之后，如果将窗口从最大化切换到正常模式，就会抛出异常，异常信息如下：
System.ComponentModel.Win32Exception (998): 内存位置访问无效。
   at HandyControl.Tools.Interop.InteropMethods.GetWindowPlacement(IntPtr hwnd)
   at HandyControl.Data.GlowEdge.UpdateWindowPos()
   at HandyControl.Controls.GlowWindow.UpdateGlowWindowPositions(Boolean delayIfNecessary)
   at HandyControl.Controls.GlowWindow.OnDelayedVisibilityTimerTick(Object sender, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.DispatcherTimer.<>c.<Restart>b__21_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
但似乎只是抛出了异常，处理异常后并不会影响程序的正常运行，我的环境是.Net 7，HandyControl版本为3.4.0，IDE是Rider 2023.2，系统是Windows 10 22H2

### Steps to reproduce the bug

我没有尝试复现，因此不保证能够成功复现此问题

### Expected behavior

期望的情况是不抛出任何异常

### Screenshots

![image](https://github.com/HandyOrg/HandyControl/assets/112372629/3ae9c64e-e3dd-4270-8e86-b9797c22b727)
这是我GlowWindow的属性

### NuGet package version

HandyControl 3.4.0

**Comment by Anestis271** [comment]
我大概知道了产生此异常的原因，因为我的个人疏忽将程序publish到了x86平台因此才产生了该异常。
